### ISSUE TITLE
本地安装会遇到一些问题，不知道是普遍还是 我的个例。

### ISSUE THREAD

**Issue by zhangblin** [jourdon/laravel_admin_layui#1]
使用git clone   https://github.com/jourdon/laravel_admin_layui.git 下载
1、提示 artisan 命令   php artisan migrate
   提示：
Warning: require(D:\wamp\www\laravel\laravel_admin_layui/vendor/autoload.php): failed to open stream: No such file or directory in D:\wamp\www\laravel\laravel_admin_layui\artisan on line 18
Fatal error: require(): Failed opening required 'D:\wamp\www\laravel\laravel_admin_layui/vendor/autoload.php' (include_path='.;C:\php\pear') in D:\wamp\www\laravel\laravel_admin_layui\artisan on line 18
解决方案： composer update  
2、提示 
  In Connection.php line 664:
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (S
  QL: alter table `users` add unique `users_email_unique`(`email`))
In Connection.php line 458:
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

 解决方案：
   在app/Providers/AppServiceProvider.php 的boot 方法中 加入 
     Schema::defaultStringLength(191); 
    命名空间  use Illuminate\Support\Facades\Schema;

**Comment by jourdon** [comment]
@zhangblin  谢谢提醒 
composer update  忘记加上去了。
第 2 个问题，我刚查了一下。应该是 mysql 版本的问题。如果是 mysql 5.3以下,会有这个问题。所以建议升级 Mysql 版本
