### ISSUE TITLE
为什么会出现列表无法显示完整

### ISSUE THREAD

**Issue by candivan** [jourdon/laravel_admin_layui#2]
显示20条数据时候会出现如下截图问题

![1](https://user-images.githubusercontent.com/26474092/35036079-281272ec-fbae-11e7-961c-4d5f62d2b7d3.png)

**Comment by jourdon** [comment]
@candivan   参考 layui 文档 -〉数据表格-〉最大化适应   添加如果代码

```
,height: 'full-200'
```
如果超过高度会自动出滚动条
